AWSTemplateFormatVersion: '2010-09-09'

Description: Sample CloudFormation template with YAML - DynamoDB Definition depends on sample-vpc-cfn.yml

Parameters:
  VPCName:
    Description: Target VPC Stack Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: mynavi-sample-cloudformation-vpc
  EnvType:
    Description: Which environments to deploy your service.
    Type: String
    AllowedValues: ["Dev", "Staging", "Production"]
    Default: Dev
Conditions:
  ProductionResources: {"Fn::Equals" : [{"Ref":"EnvType"}, "Production"]}
  StagingResources: !Equals [ !Ref EnvType, "Staging"]
  DevResources: {"Fn::Equals" : [{"Ref":"EnvType"}, "Dev"]}

Resources:
  DynamoDBSampleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !If ["ProductionResources", sample-table,  !If ["StagingResources", "staging_sample-table", "dev_sample-table"]]
      BillingMode: PROVISIONED
      SSESpecification: !If ["ProductionResources", { "SSEEnabled" : true }, !Ref "AWS::NoValue"]
      AttributeDefinitions:
        - AttributeName: samplePartitionKey
          AttributeType: S
        - AttributeName: sampleSortKey
          AttributeType: S
      KeySchema:
        - AttributeName: samplePartitionKey
          KeyType: HASH
        - AttributeName: sampleSortKey
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  DynamoDBProduction:
    Condition: "ProductionResources"
    Description: DynamoDB SampleTable for Production
    Value: !Ref DynamoDBSampleTable
    Export:
      Name: !Sub ${VPCName}-DynamoDBProductionSampleTable
  DynamoDBStaging:
    Condition: "StagingResources"
    Description: DynamoDB SampleTable for Staging
    Value: !Ref DynamoDBSampleTable
    Export:
      Name: !Sub ${VPCName}-DynamoDBStagingSampleTable
  DynamoDBDev:
    Condition: "DevResources"
    Description: DynamoDB SampleTable for Dev
    Value: !Ref DynamoDBSampleTable
    Export:
      Name: !Sub ${VPCName}-DynamoDBDevSampleTable