AWSTemplateFormatVersion: '2010-09-09'

Description: Sample CloudFormation template with YAML - ALB.  Depends On sample-vpc-cfn.yml, sample-sg-cfn.yml.

Mappings:
  DeployEnvironmentMap:
    Production:
      "Protocol": "HTTPS"
      "Port": 443
    Staging:
      "Protocol": "HTTP"
      "Port": 80
    Dev:
      "Protocol": "HTTP"
      "Port": 80

Parameters:
  VPCName:
    Description: Target VPC Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: mynavi-sample-cloudformation-vpc
  EnvType:
    Description: Which environments to deploy your service.
    Type: String
    AllowedValues: ["Dev", "Staging", "Production"]
    Default: Dev

  FrontendHealthCheckPath:
    Description: Frontend WebApp health check path
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[-짜.짜/a-zA-Z0-9]*$
    Default: /frontend/index.html

  BackendDefaultHealthCheckPath:
    Description: Backend Service Default health check path
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[-짜.짜/a-zA-Z0-9]*$
    Default: /backend/api/v1/users

Resources:
  FrontendALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: FrontendALB
      Subnets:
        - Fn::ImportValue: !Sub ${VPCName}-PublicSubnet1
        - Fn::ImportValue: !Sub ${VPCName}-PublicSubnet2
      SecurityGroups:
        - Fn::ImportValue: !Sub ${VPCName}-SecurityGroupFrontendALB

  FrontendALBDefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: FrontendALBTargetGroup
      VpcId:
        Fn::ImportValue: !Sub ${VPCName}-VPCID
      Port: !FindInMap [DeployEnvironmentMap, !Ref EnvType, Port]
      Protocol: !FindInMap [DeployEnvironmentMap, !Ref EnvType, Protocol]
      HealthCheckPath: !Ref FrontendHealthCheckPath
      HealthyThresholdCount: 2
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '20'

  FrontendALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref FrontendALB
      Port: !FindInMap [DeployEnvironmentMap, !Ref EnvType, Port]
      Protocol: !FindInMap [DeployEnvironmentMap, !Ref EnvType, Protocol]
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref FrontendALBDefaultTargetGroup

  BackendALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: BackendALB
      Subnets:
        - Fn::ImportValue: !Sub ${VPCName}-PrivateSubnet1
        - Fn::ImportValue: !Sub ${VPCName}-PrivateSubnet2
      SecurityGroups:
        - Fn::ImportValue: !Sub ${VPCName}-SecurityGroupBackendALB

  BackendALBDefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: BackendALBDefaultTargetGroup
      VpcId:
        Fn::ImportValue: !Sub ${VPCName}-VPCID
      Port: !FindInMap [DeployEnvironmentMap, !Ref EnvType, Port]
      Protocol: !FindInMap [DeployEnvironmentMap, !Ref EnvType, Protocol]
      HealthCheckPath: !Ref BackendDefaultHealthCheckPath
      HealthyThresholdCount: 2
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '20'

  BackendALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref BackendALB
      Port: !FindInMap [DeployEnvironmentMap, !Ref EnvType, Port]
      Protocol: !FindInMap [DeployEnvironmentMap, !Ref EnvType, Protocol]
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref BackendALBDefaultTargetGroup

Outputs:
  FrontendALB:
    Description: Frontend ALB
    Value: !Ref FrontendALB
    Export:
      Name: !Sub ${VPCName}-Frontend-ALB

  BackendALB:
    Description: Backend ALB
    Value: !Ref BackendALB
    Export:
      Name: !Sub ${VPCName}-Backend-ALB

  FrontendALBDNS:
    Description: Public DNS Name
    Value: !GetAtt FrontendALB.DNSName
    Export:
      Name: !Sub ${VPCName}-FrontendALBDNS

  BackendALBDNS:
    Description: Private DNS Name
    Value: !GetAtt BackendALB.DNSName
    Export:
      Name: !Sub ${VPCName}-BackendALBDNS

  FrontendALBDefaultTargetGroup:
    Description: Frontend TagetGroup Default
    Value: !Ref FrontendALBDefaultTargetGroup
    Export:
      Name: !Sub ${VPCName}-Frontend-ALB-DefaultTargetGroup

  BackendALBDefaultTargetGroup:
    Description: Backend TagetGroup Default
    Value: !Ref BackendALBDefaultTargetGroup
    Export:
      Name: !Sub ${VPCName}-Backend-ALB-DefaultTargetGroup

  FrontendALBListener:
    Description: Frontend ALB Listener
    Value: !Ref FrontendALBListener
    Export:
      Name: !Sub ${VPCName}-Frontend-ALB-Listener

  BackendALBListener:
    Description: Backend ALB Listener
    Value: !Ref BackendALBListener
    Export:
      Name: !Sub ${VPCName}-Backend-ALB-Listener
