AWSTemplateFormatVersion: '2010-09-09'

Description: Sample CloudFormation template with YAML - S3 Bucket Definition

Parameters:
  EnvType:
    Description: Which environments to deploy your service.
    Type: String
    AllowedValues: ["dev", "staging", "production"]
    Default: dev
  S3BucketName:
    Description: The BacketName.
    Type: String
    Default: debugroom-mynavi-sample-cloudformation-bucket

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${S3BucketName}-${EnvType}
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

Outputs:
  S3Bucket:
    Description: Mynavi S3 bucket name
    Value: !Ref S3Bucket
    Export:
      Name: !Sub MynaviSampleS3Bucket-${EnvType}