server:
  port: 8081
cloud:
  aws:
    credentials:
      profileName:
      instanceProfile: false
    stack:
      auto: false
    region:
      auto: false
      static: ap-northeast-1
#ElasitiCache is not permitted public access, use local redis server except dev environment in vpc.
#spring:
#  redis:
#    host: ${REDIS_CLUSTER_ENDPOINT:localhost}
#    port: ${REDIS_CLUSTER_PORT:6379}
